development:
  adapter: postgresql
  encoding: unicode
  database: byodeal_development
  pool: 5
  username: daimler456
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: byodeal_test
  pool: 5
  username: daimler456
  password:
